import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {fixture} from './support.mjs';
import {run} from '../scripts/fusion-state.mjs';
import {acquire,release} from '../scripts/writer-lease.mjs';
import {snapshot,changes} from '../scripts/artifact.mjs';
import {config,selectExecutor} from '../scripts/executor-config.mjs';

// 한 일꾼을 n번 반려한다. 매번 다른 반려 사유를 써서 "같은 실수 반복" 교체 규칙을 피한다.
const grind=(f,n)=>{for(let i=0;i<n;i++){f.begin();f.finish();f.review('redo',['AC'+f.state().iteration]);}};

test('explicit Grok goes to work first; Opus holds no attempt',t=>{const f=fixture(t);assert.equal(f.state().initial_executor,'grok');assert.equal(f.state().routing.mode,'explicit');assert.equal(f.begin().transport,'executor-cli');assert.deepEqual(f.state().attempts,{grok:1,antigravity:0,sonnet:0,haiku:0,luna:0,lead:0});assert.equal(f.state().lead_target_model,'claude-opus-5-5');assert.equal(f.state().lead_model,null);});
test('CLI --executor antigravity persists selection',t=>{const f=fixture(t,{initialize:false});const input=path.join(f.temp,'brief.json');fs.writeFileSync(input,JSON.stringify(f.brief));execFileSync(process.execPath,[fileURLToPath(new URL('../scripts/fusion-state.mjs',import.meta.url)),'init',f.root,input,'--executor','antigravity']);assert.equal(f.state().initial_executor,'antigravity');});
test('Opus and Claude cannot be hired as workers, Sol only reviews',t=>{const f=fixture(t,{initialize:false});for(const executor of ['claude','opus'])assert.throws(()=>run(f.root,'init',{...f.brief,executor}),/lead, not a worker/);assert.throws(()=>run(f.root,'init',{...f.brief,executor:'sol'}),/only reviews/);assert.ok(!fs.existsSync(path.join(f.control,'state.json')));});
test('Codex lead config from main is rejected, not silently converted',t=>{const f=fixture(t,{initialize:false});fs.writeFileSync(path.join(f.root,'hyperfusion.config.json'),JSON.stringify({lead:'sol',external:{default:'claude',available:['claude']}}));assert.throws(()=>config(f.root),/main branch/);});
test('configured default is honored',t=>{const f=fixture(t,{initialize:false});fs.writeFileSync(path.join(f.root,'hyperfusion.config.json'),JSON.stringify({external:{default:'antigravity',available:['grok','antigravity']}}));assert.equal(selectExecutor(config(f.root)),'antigravity');assert.equal(run(f.root,'init',{...f.brief,executor:undefined}).initial_executor,'antigravity');});
test('re-dispatch without concrete orders is refused',t=>{const f=fixture(t);f.begin();f.finish();f.review('redo');assert.throws(()=>run(f.root,'begin',f.brief),/lead_feedback/);assert.equal(f.state().attempts.grok,1);assert.equal(f.begin().transport,'executor-cli');});
test('rejection without blocking criteria is refused',t=>{const f=fixture(t);f.begin();f.finish();assert.throws(()=>run(f.root,'review',{verdict:'redo',rationale:'meh',blocking_criteria:[],commands_run:[],independent_diff_review:true}),/concrete blocking/);});
test('same blocking reason twice gets the worker replaced',t=>{const f=fixture(t);f.begin();f.finish();f.review('redo',['AC1']);f.begin();f.finish();assert.equal(f.review('redo',['AC1']).phase,'ALTERNATIVE_REQUIRED');assert.equal(f.begin({executor:'antigravity'}).executor,'antigravity');});
test('alternative switches worker immediately and keeps the bench session',t=>{const f=fixture(t);f.begin();const grokSession=f.state().sessions.grok;f.finish();assert.equal(f.review('alternative').phase,'ALTERNATIVE_REQUIRED');assert.throws(()=>f.begin({executor:'grok'}),/different executor/);f.begin({executor:'antigravity'});f.finish();f.review('alternative');const back=f.begin({executor:'grok'});assert.equal(back.cli.session_id,grokSession);assert.ok(back.cli.resume);});
test('takeover is refused while any worker has budget',t=>{const f=fixture(t);f.begin();f.finish();assert.throws(()=>f.review('takeover'),/make them work/);assert.equal(f.state().phase,'REVIEW');});
test('all workers exhausted after three rounds each, then exactly one lead takeover',t=>{const f=fixture(t);grind(f,3);assert.equal(f.state().phase,'ALTERNATIVE_REQUIRED');for(const e of ['antigravity','sonnet','haiku','luna']){f.begin({executor:e});f.finish();f.review('redo',['X'+e]);grind(f,2);}assert.deepEqual(f.state().attempts,{grok:3,antigravity:3,sonnet:3,haiku:3,luna:3,lead:0});assert.equal(f.state().phase,'TAKEOVER_REQUIRED');assert.throws(()=>f.begin(),/recorded reason/);assert.equal(f.begin({takeover_reason:'Twelve worker rounds failed on AC1'}).transport,'lead-takeover');assert.equal(f.state().writer.owner,'lead');f.finish();assert.equal(f.review('redo').phase,'BLOCKED');assert.throws(()=>f.begin());});
test('lead_takeover:false ends in BLOCKED instead of Opus coding',t=>{const f=fixture(t,{initialize:false});fs.writeFileSync(path.join(f.root,'hyperfusion.config.json'),JSON.stringify({lead_takeover:false,external:{default:'grok',available:['grok']}}));run(f.root,'init',f.brief);grind(f,3);assert.equal(f.state().phase,'BLOCKED');});
test('single-worker pool keeps grinding the same worker',t=>{const f=fixture(t,{initialize:false});fs.writeFileSync(path.join(f.root,'hyperfusion.config.json'),JSON.stringify({external:{default:'grok',available:['grok']}}));run(f.root,'init',f.brief);f.begin();f.finish();f.review('redo',['AC1']);f.begin();f.finish();assert.equal(f.review('redo',['AC1']).phase,'REDO');assert.throws(()=>f.review('alternative'));});
test('exclusive lease rejects other writers and wrong release',t=>{const f=fixture(t);f.begin();assert.throws(()=>acquire(f.root,'other',1,'lead'),/EEXIST/);assert.throws(()=>release(f.root,'wrong'),/mismatch/);});
test('independent verification gates CLOSE',t=>{const f=fixture(t);f.begin();f.finish();assert.throws(()=>run(f.root,'verify',{}),/Invalid phase/);f.review();assert.throws(()=>run(f.root,'verify',{acceptance_satisfied:true,tests:[{command:'false',status:'fail'}]}));assert.equal(run(f.root,'verify',{acceptance_satisfied:true,tests:[{command:'check',status:'pass'}]}).phase,'CLOSE');});
test('blocked worker result cannot pass review',t=>{const f=fixture(t);f.begin();const r=f.result();r.status='blocked';r.unresolved=['gave up'];f.finish(r);assert.throws(()=>f.review(),/Incomplete/);});
test('decision needed remains with lead',t=>{const f=fixture(t);f.begin();const r=f.result();r.status='needs_decision';r.needs_lead_decision=true;f.finish(r);f.review('decision');assert.equal(run(f.root,'decide',{decision:'Preserve public API'}).phase,'REDO');});
test('invalid result keeps writer until explicit recovery',t=>{const f=fixture(t);f.begin();const token=f.state().writer.token;assert.equal(f.finish({}).phase,'RECOVERY_REQUIRED');assert.ok(fs.existsSync(path.join(f.control,'locks/writer.json')));assert.throws(()=>run(f.root,'recover',{token,reason:'inspect'}));assert.equal(run(f.root,'recover',{token,quiescent:true,reason:'Worker stopped; diff inspected'}).phase,'REDO');});
test('scope and index changes cannot pass',t=>{const f=fixture(t);f.begin();fs.writeFileSync(path.join(f.root,'outside.txt'),'bad');f.git('add','outside.txt');const s=f.finish(f.result(['outside.txt']));assert.equal(s.phase,'RECOVERY_REQUIRED');assert.ok(s.last_errors.some(e=>e.includes('Out of scope')));assert.ok(s.last_errors.includes('HEAD/index changed'));});
test('lying about changed files is caught',t=>{const f=fixture(t);f.begin();fs.writeFileSync(path.join(f.root,'a.txt'),'fixed');const s=f.finish(f.result([]));assert.ok(s.last_errors.includes('Declared changes differ from snapshot'));});
test('dirty user changes included in baseline and preserved',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.root,'user.txt'),'user');const base=snapshot(f.root);f.begin();fs.writeFileSync(path.join(f.root,'a.txt'),'fixed');f.finish(f.result(['a.txt']));assert.deepEqual(changes(base,snapshot(f.root)),['a.txt']);assert.equal(fs.readFileSync(path.join(f.root,'user.txt'),'utf8'),'user');});
test('tree drift blocks review',t=>{const f=fixture(t);f.begin();f.finish();fs.writeFileSync(path.join(f.root,'a.txt'),'late');assert.throws(()=>f.review(),/drift/);assert.equal(f.state().phase,'RECOVERY_REQUIRED');});
test('control lock rejects overlapping controller commands',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.control,'locks/control.lock'),'');assert.throws(()=>f.begin(),/EEXIST/);assert.equal(f.state().iteration,0);});
test('orphan lease recovery preserves consumed budget',t=>{const f=fixture(t),lease=acquire(f.root,f.brief.task_id,1,'grok');run(f.root,'recover',{token:lease.token,quiescent:true,reason:'Controller stopped before dispatch'});assert.equal(f.state().attempts.grok,1);f.begin();assert.equal(f.state().attempts.grok,2);});
test('unavailable CLI preflight consumes no attempt or lease',t=>{const f=fixture(t);process.env.HF_GROK_BIN=path.join(f.temp,'missing');assert.throws(()=>f.begin(),/ADAPTER_UNAVAILABLE/);assert.equal(f.state().iteration,0);assert.ok(!fs.existsSync(path.join(f.control,'locks/writer.json')));});
test('blanket Bash rule is rejected before mutation',t=>{const f=fixture(t);assert.throws(()=>f.begin({executor_bash_rules:['Bash(*)']}),/executor_bash_rules/);assert.equal(f.state().iteration,0);});
test('path traversal rejected before mutation',t=>{const f=fixture(t);assert.throws(()=>f.begin({scope:{paths:['../oops'],allowed_expansion:'ask-lead'}}));assert.equal(f.state().iteration,0);});
test('main-branch state requires explicit archive and preserves source',t=>{
 const f=fixture(t);f.begin();const old=f.state(),token=old.writer.token;old.schema_version=3;
 fs.writeFileSync(path.join(f.control,'state.json'),JSON.stringify(old));
 assert.equal(run(f.root,'status').legacy,true);assert.throws(()=>f.begin(),/LEGACY_STATE/);
 assert.throws(()=>run(f.root,'archive',{reason:'not enough'}));
 assert.equal(run(f.root,'archive',{token,quiescent:true,reason:'No process launched; preserve legacy state'}).phase,'ARCHIVED');
 assert.equal(fs.readFileSync(path.join(f.root,'a.txt'),'utf8'),'base');
 assert.equal(run(f.root,'init',{...f.brief,task_id:'HF-new'}).schema_version,4);
});
